minimumReleaseAgeExclude:
  - '@triggerix/core'
  - '@triggerix/registry'
  - '@types/node'
  - '@triggerix/runtime'

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*

allowBuilds:
  esbuild: true
  simple-git-hooks: true
